In [1]:
import pandas as ps
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from matplotlib import pyplot as plt

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [5]:
len(X_test)

540

**Logistic Regression**

In [11]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

**SVM**

In [19]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.37962962962962965

**Random Forest**

In [24]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

**K-Fold cross validation**

Basic Example

In [25]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**using K-Fold for our digits example**

In [27]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [28]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [30]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test =  \
    digits.data[train_index], digits.data[test_index], \
    digits.target[train_index], digits.target[test_index]

    scores_logistic.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [31]:
scores_logistic

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [32]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [33]:
scores_rf

[0.9248747913188647, 0.9482470784641068, 0.9165275459098498]

**Cross Validation Function**

In [34]:
from sklearn.model_selection import cross_val_score

In [36]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target, cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [37]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [40]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93489149, 0.95158598, 0.92320534])

**Parameter tunning using k fold cross validation**

In [46]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)
scores1.mean()

np.float64(0.8792799503414029)

In [47]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

np.float64(0.9376784605834884)

In [48]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
scores3.mean()

np.float64(0.9465735567970205)

In [49]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
scores4.mean()

np.float64(0.9454469273743016)

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.